GET http://localhost:5028/postings

###
GET http://localhost:5028/postings/1

###
GET http://localhost:5028/postings/999

###
POST http://localhost:5028/postings
Content-Type: application/json

{
  "from": "Ivan",
  "to": "Olena",
  "content": "Documents",
  "deliveryType": "Department",
  "weight": 2.0,
  "width": 20,
  "height": 15,
  "depth": 2,
  "value": 100
}

###
GET http://localhost:5028/postings

###
PUT http://localhost:5028/postings/1
Content-Type: application/json

{
  "id": 1,
  "from": "Alice",
  "to": "Bob",
  "content": "Books (updated)",
  "deliveryType": "Courier",
  "weight": 3.0,
  "width": 30,
  "height": 20,
  "depth": 10,
  "value": 75.0,
  "price": 125.0
}

###
GET http://localhost:5028/postings/1

###
DELETE http://localhost:5028/postings/1

###
GET http://localhost:5028/postings/1